@startuml

package Email <<Rectangle>>{
class Email
class Archive
class Deleted
class Draft
class EmailManager
class Inbox
class Junk
class Sent
}
class Command

class Email {
- from: String
- to: ArrayList<String>
- subject: String
- time: String
- content: String
- tag: ArrayList<String>
- isRead: boolean
+ void setRead(boolean isRead)
+ void setFrom(String)
+ void setTo(String)
+ void setTo(ArrayList<String>)
+ void setSubject(String)
+ void setContent(String)
+ void setTags(int[] indices)
+ String getFrom()
+ String getTo()
+ String getSubject()
+ String getContent()
- String getStatus()
+ String toString()
+ String getShortDescription()
+ ArrayList<String> getTags
+ static String[] getAvailableTags()
- ArrayList<String> stringToList(String to)
}

class EmailManager {
- emailsList: ArrayList<Email>
- listedEmailsList: ArrayList<Email>
- listedType: String
+ static ArrayList<Email> getEmailsList()
+ int getNumOfEmails()
+ int getNumOfArchiveEmails()
+ int getNumOfDeletedEmails()
+ int getNumOfDraftEmails()
+ int getNumOfInboxEmails()
+ int getNumOfJunkEmails()
+ int getNumOfSentEmails()
+ static void printEmailByType(ArrayList<Email>)
+ void setListedType(String emailType)
+ String getListedType()
+ void sortBySender()
+ void sortByTime()
+ static ArrayList<Email> getArchivedEmails()
+ static ArrayList<Email> getDeletedEmails()
+ static ArrayList<Email> getDraftEmails()
+ static ArrayList<Email> getInboxEmails()
+ static ArrayList<Email> getJunkEmails()
+ static ArrayList<Email> getSentEmails()
+ static ArrayList<Email> getAllEmails()
+ static ArrayList<Email> getListedEmailsList()
+ void deleteEmail(Email)
+ void addToDeleted(Email)
+ void addToArchive(Email)
+ void addToDraft(Email)
+ ArrayList<Email> findByString(ArrayList<Email> emails, String filterString)

}

Archive ---|> Email
Deleted ---|> Email
Draft ---|> Email
Inbox ---|> Email
Junk ---|> Email
Sent ---|> Email
EmailManager ---> Email :uses
Command --left-> Email: uses
Command --left-> EmailManager: uses

@enduml