@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

class Mojo
class Ui
class Parser
class EmailManager
class Command
class Email

Mojo --|> EmailManager
Mojo --|> Ui
Mojo --|> Storage
Mojo --|> Parser
Mojo --|> Command

Command ..|> EmailManager
Command ..|> Ui
Command ..|> Storage

EmailManager --|> Email

@enduml