@startuml
'https://plantuml.com/sequence-diagram

participant ":ComposeCommand" as ComposeCommand
participant "<<class>>\n:Parser" as Parser
participant ":EmailManager" as EmailManager
participant ":Draft" as Draft
participant ":Ui" as Ui
participant ":Storage" as Storage
hide footbox

 -> ComposeCommand : execute()
activate ComposeCommand

ComposeCommand -> Ui : printComposeUi()
activate Ui
deactivate Ui

-> ComposeCommand : Input receiver's email address
ComposeCommand -> Parser : parseRecipients(userInput)
activate Parser
return email address
deactivate Parser

-> ComposeCommand : Input subject and content
create Draft
ComposeCommand -> Draft : constructor()
activate Draft
return draft email
deactivate Draft

ComposeCommand -> EmailManager : addToDraft()
activate EmailManager
deactivate EmailManager

ComposeCommand -> ComposeCommand : check validity of email address,\n subject, and content
activate ComposeCommand
ComposeCommand -> ComposeCommand
deactivate ComposeCommand

ComposeCommand -> EmailManager : getEmailList()
activate EmailManager
EmailManager ---> ComposeCommand
deactivate EmailManager

ComposeCommand -> Storage : updateAllTypeEmails()
activate Storage
deactivate Storage

ComposeCommand -> Ui : printEmailDrafted()
activate Ui
deactivate Ui

@enduml