@startuml
'https://plantuml.com/sequence-diagram

participant ":TagCommand" as TagCommand
participant ":Parser" as Parser
participant ":EmailManager" as EmailManager
participant ":Email" as Email

[-> TagCommand: execute()
activate TagCommand

TagCommand -> Parser: extractTags(userInput)
activate Parser
Parser --> TagCommand: index
deactivate Parser

TagCommand -> EmailManager: getListedEmailsList()
activate EmailManager
EmailManager --> TagCommand: listedEmails
deactivate EmailManager

TagCommand -> Email: setTags(indices)
activate Email
Email --> TagCommand: tags
deactivate Email

[<- TagCommand
deactivate TagCommand

@enduml